version: '3'

services:
    mariadb:
        image: mariadb:latest
        container_name: MariaDB
        restart: always
        ports:
            - 3306:3306
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: mariadb
            MYSQL_USER: mariadb
            MYSQL_PASSWORD: mariadb
