version: '3'

services:
    redis:
        image: redis:alpine
        container_name: Redis
        restart: always
        ports:
            - 6379:6379
        volumes:
            - ./data:/data
            - ./data/redis.conf:/usr/local/etc/redis/redis.conf
        # command: redis-server --requirepass root
        command: redis-server
